
export const GET_ALL_COMMENTS_SAGA = 'GET_ALL_COMMENTS_SAGA'
export const GET_ALL_COMMENTS = 'GET_ALL_COMMENTS'

export const INSERT_COMMENT_SAGA = 'INSERT_COMMENT_SAGA'
export const INSERT_COMMENT = 'INSERT_COMMENT'
export const DELETE_COMMENT_SAGA = 'DELETE_COMMENT_SAGA'
export const UPDATE_COMMENT_SAGA = 'UPDATE_COMMENT_SAGA'
