export const GET_USER_BY_PROJECT_ID_SAGA = 'GET_USER_BY_PROJECT_ID_SAGA';
export const GET_USER_BY_PROJECT_ID = 'GET_USER_BY_PROJECT_ID';

export const SIGN_UP_USER_SAGA = 'SIGN_UP_USER_SAGA';

export const GET_LIST_USER_SAGA = 'GET_LIST_USER_SAGA';
export const GET_LIST_USER = 'GET_LIST_USER';
export const EDIT_USER = 'EDIT_USER';
export const EDIT_USER_SAGA = 'EDIT_USER_SAGA';
export const SET_SUBMIT_EDIT_USER = 'SET_SUBMIT_EDIT_USER';
export const DELETE_USER_SAGA = 'DELETE_USER_SAGA';